[package]
name = "match_expressions"
version = "0.1.0"
edition = "2021"
# This exercise is independent, not part of the workspace
[workspace]


# This exercise demonstrates pattern matching without external dependencies
[dependencies]