[package]
name = "error_handling"
version = "0.1.0"
edition = "2021"
# This exercise is independent, not part of the workspace
[workspace]


# This exercise demonstrates error handling without external dependencies
[dependencies]