[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"
# This exercise is independent, not part of the workspace
[workspace]


# This is a simple exercise with no external dependencies
[dependencies]