[package]
name = "loops"
version = "0.1.0"
edition = "2021"
# This exercise is independent, not part of the workspace
[workspace]


# This exercise demonstrates loops with random number generation
[dependencies]
rand = "0.8"