[package]
name = "game_enhancements"
version = "0.1.0"
edition = "2021"

# Enhanced guessing game with advanced features
[dependencies]
rand = "0.8"

# Optional: Add these for even more advanced features
# serde = { version = "1.0", features = ["derive"] }
# serde_json = "1.0"