[package]
name = "complete_game"
version = "0.1.0"
edition = "2021"
# This exercise is independent, not part of the workspace
[workspace]


# Complete guessing game using rand for random number generation
[dependencies]
rand = "0.8"